config/routes.rb
Rails.application.routes.draw do
  resources :stocks
  root "stocks#index"
  end

app/models/stock.rb
class Stock < ActiveRecord::Base
  validates :buyprice, presence: { strict: true }
  validates :symbol, uniqueness: true
  validate :symbol_exist_externally
  def symbol_exist_externally
    stock = StockQuote::Stock.quote(symbol)
    if stock.failure?
      errors.add(:symbol)
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

end

app/controllers/stocks_controller.rb
class StocksController < ApplicationController
  before_action :find_stock, only: [:show, :edit, :update, :destroy ]

  def index
    @stock = Stock.all.order("created_at DESC")
  end

  def show

  end

  def navbar
    @stock = Stock.all.order("created_at DESC")
  end

  def new
    @stock = Stock.new
  end

  def create
    @stock = Stock.new(stock_params)

    if @stock.save
      redirect_to root_path, notice: "Successfully created new Stock"
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @stock.update(stock_params)
      redirect_to @stock
    else
      render 'edit'
    end
  end

  def destroy
    @stock.destroy
    redirect_to root_path, notice: "Successfully deleted Stock"
  end

  private
  def find_stock
    @stock = Stock.find(params[:id])
  end

  def stock_params
    params.require(:stock).permit(:symbol, :eps, :dividend_yield, :yield, :discrate, :buyprice)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def is_active?(link_path)
    if current_page?(link_path)
      "active"
    else
      ""
    end
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/stocks_helper.rb
module StocksHelper

end

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title Stock Value
  = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags
%body
  = render partial: "shared/navbar"
  %br/
  = yield

app/views/shared/_dcf.html.haml
%h2 dcf

app/views/shared/_ggm.html.haml
%p name

app/views/shared/_navbar.html.haml
%nav.navbar.navbar-default
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle.collapsed{"aria-expanded" => "false", "data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      .navbar-brand=link_to image_tag('bull.png')
    / Collect the nav links, forms, and other content for toggling
    #bs-example-navbar-collapse-1.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        %li{class: current_page?(root_path) && 'active'}
          = link_to "Home",root_path
        %li{class: current_page?(new_stock_path) &&  'active'}
          = link_to "Add Stock", new_stock_path
    / /.navbar-collapse
  / /.container-fluid

app/views/shared/_overview.html.haml
%table.table.table-striped
  %caption= Time.now.year+1
  %thead
    %tr
      %th Estimates
      %th Value
  %tbody
    %tr
      %th{:scope => "row"} Price Paid
      %td last_trade_price_only
    %tr
      %th{:scope => "row"}  Earnings/share
      %td earnings_share
    %tr
      %th{:scope => "row"} Price/Earnings
      %td pe_ratio
    %tr
      %th{:scope => "row"} Dividend
      %td dividend_yield
    %tr
      %th{:scope => "row"} Profit margin
      %td
    %tr
      %th{:scope => "row"} Earnings/share
      %td eps_estimate_current_year
%br/
.row
.text-center.col-md-12
  %table.table.table-striped
    %caption Recommendations:
    %thead
      %tr
        %th Value
        %th Discount
    %tbody
      %tr
        %th{:scope => "row"} Estimated Price
        %td (last_trade_price_only*eps_estimate_next_year)
      %tr
        %th{:scope => "row"}  Rebate
        %td eps_estimate_next_year

app/views/stocks/_form.html.haml
= simple_form_for @stock, html: { multipart: true} do |f|
  - if @stock.errors.any?
    #errors
      %p
        %p.red Error prevented this stock from saving

      %ul
        - @stock.errors.full_messages.each do |msg|
          %li.red= msg
  .panel_body
    = f.input :symbol, label: "Ticker Symbol", input_html: { class: 'form-control'}
    = f.input :buyprice, label: "Buy price", input_html: { class: 'form-control'}
    %br/
    = f.button :submit, class: 'btn btn-primary'

app/views/stocks/edit.html.haml
.row
.text-center.col-xs-12.col-sm-6.col-md-6
  %h1 Edit Stock
  = render 'form'

%br/

app/views/stocks/index.html.haml
%br/

%table.table.table-striped
  %tr
    %th Name
    %th Symbol
    %th Last trade price
    %th Your buy price
    %th win/loss
    %th +/-%
    %th Target Exit price
    %th
    %th P/E
    %th earnings / share


    - @stock.each do |stocks|
      - quote = StockQuote::Stock.quote(stocks.symbol)
      %tr
        %td= link_to quote.name, stocks # Name
        %td= link_to quote.symbol, stocks # Symbol
        %td= quote.last_trade_price_only #Last trade price
        %td= stocks[:buyprice] #Your buy price
        - percent_change = number_to_percentage((quote.last_trade_price_only/stocks[:buyprice]-1)*100)
        - if percent_change.include? '-'
          %td.red= number_with_precision(quote.last_trade_price_only-stocks[:buyprice], precision: 2) # Win/Loss
          %td.red= number_with_precision(percent_change.to_f, precision: 1)+'%' # Percentage -
        - else
          %td.green= number_with_precision(quote.last_trade_price_only-stocks[:buyprice], precision: 2) # Win/Loss
          %td.green= number_with_precision(percent_change.to_f, precision: 1)+'%' # Percentage +
        %td= quote.oneyr_target_price #Target exit price
        %td
        %td= quote.pe_ratio # P/E Ratio   last_trade_price_only / earnings_share
        %td= quote.earnings_share #earnings share


%br

app/views/stocks/new.html.haml
.row
.text-center.col-md-4.col-md-offset-4
  %h3 Add new stock

  = render 'form'

%br/
.row
.text-center.col-md-4.col-md-offset-4
= link_to "Back", root_path, class: 'btn btn-default'

app/views/stocks/show.html.haml
- quote = StockQuote::Stock.quote(@stock.symbol)
.text-center.col-md-4.col-md-offset-4
  %h3= quote.name
.row
.col-xs-12.col-sm-6.col-md-6
  .tabbable
    %ul.nav.nav-tabs
      %li.active
        %a{"data-toggle" => "tab", :href => "#2016"} Overview
    .tab-content
      #2016.tab-pane.active
        %table.table.table-striped
          %caption= Time.now.year
          %thead
            %tr
              %th Current
              %th Value
          %tbody
            %tr
              %th{:scope => "row"} Price Paid
              %td= @stock[:buyprice]
            %tr
              %th{:scope => "row"}  Earnings/share
              %td eps_estimate_current_year
            %tr
              %th{:scope => "row"} Price/Earnings
              %td pe_ratio
            %tr
              %th{:scope => "row"} Dividend
              %td dividend_yield
            %tr
              %th{:scope => "row"} Profit margin
              %td earnings_share
            %tr
              %th{:scope => "row"} Earnings/share
              %td eps_estimate_current_year
  = link_to "Back", root_path, class: 'btn btn-default'
  = link_to "Edit", edit_stock_path, class: 'btn btn-default'
  = link_to "Delete", stock_path, method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-default'

// The below will be yielded depending on the model
.col-xs-12.col-sm-6.col-md-6
.tabbable
  %ul.nav.nav-tabs
    %li.active
      %a{"data-toggle" => "tab", :href => "#tab1"} Overview
    %li
      %a{"data-toggle" => "tab", :href => "#tab2"}  Gordon Growth Model
    %li
      %a{"data-toggle" => "tab", :href => "#tab3"}  Discounted Cash Flow
  .tab-content
    #tab1.tab-pane.active
      = render partial: "shared/overview"
    #tab2.tab-pane
      = render partial: "shared/ggm"
    #tab3.tab-pane
      = render partial: "shared/dcf"


// The above will be yielded from different pages